scan_timeout = 5

[cmd_duration]
format = '[ \[$duration\]]($style)'
style = "yellow"

[[battery.display]]
threshold = 20
style = "bold red"

[character]
success_symbol = "[ ➜](bold green) "
error_symbol = "[ ✗](bold red) "

[directory]
read_only = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))' 
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
up_to_date = "✓(green)"
untracked = '[?\($count\) ](bold yellow)'
modified = '[~\($count\) ](bold blue)'
staged = '[+\($count\) ](bold green)'
renamed = "➜"
deleted = '[-\($count\) ](bold red)'
style = "purple"

[java]
symbol = " "
format = '[ \[$symbol($version)\]]($style)'
style = "bold blue"


[lua]
format = '[ \[$symbol($version)\]]($style)'
symbol = "☽ "
style = "blue"

[nodejs]
format = '[ \[$symbol($version)\]]($style)'
symbol = " "
style = "green"

[package]
format = '[ \[$symbol$version\]]($style)'
symbol = " "
style = "yellow"

[python]
symbol = " "
format = '[ \[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))\]]($style)'

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[ $user]($style) "
disabled = false
show_always = true
