format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""
# $cmd_duration\

scan_timeout = 5

[username]
style_user = "blue bold"
style_root = "red bold"
# format = "[ /ﳟ//גּ/ﭾ////// ]($style) "
format = "[  ]($style) "
disabled = false
show_always = true

[line_break]
disabled = true

[[battery.display]]
threshold = 20
style = "bold red"

[character]
success_symbol = "[ ](bold green) "
# success_symbol = "[ ❯](bold green) "
error_symbol = "[ ✗](bold red) "
disabled = true

[directory]
read_only = " "
style = "bold green"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold #6C7A96"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bright-black"
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
up_to_date = ""
untracked = '[?$count ](bright-black)'
modified = '[~$count ](bright-black)'
staged = '[+$count ](bright-black)'
renamed = '[➜$count ](bright-black)'
deleted = '[-$count ](bright-black)'

# [cmd_duration]
# format = '[$duration]($style)'
# style = "yellow"
