format = """
[  ](#3B4252)\
$directory\
[  ](#3B4252)\
$git_branch\
$git_state\
$line_break\
$character\
[](#3B4252)"""
# $username\
# $hostname\

right_format = """
$git_status\
"""
# $cmd_duration

scan_timeout = 5

[username]
# style_user = "blue bold"
# style_root = "red bold"
style_root = "red bold"
# format = "[ /ﳟ//גּ/ﭾ////// ]($style) "
format = "[]($style) "
disabled = false
show_always = true

[line_break]
disabled = true

[[battery.display]]
threshold = 20
style = "bold red"

[character]
success_symbol = "[ ](bold green) "
# success_symbol = "[ ❯](bold green) "
error_symbol = "[ ✗](bold red) "
disabled = true

[directory]
read_only = " "
# style = "bold green"
style = "bold bg:#3B4252 fg:#81A1C1"
format = "[ $path ]($style)"

[directory.substitutions]
# "Documents" = "  "
# "Pictures" = "  "
"melaneyroot.github.io" = "melaney  "
"nvim" = "  "
"Downloads" = "  "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold #6C7A96"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bright-black"
# ahead = "⇡${count} "
ahead = "◎ ${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
up_to_date = ""
# untracked = '[?$count ](bright-black)'
# modified = '[~$count ](bright-black)'
# staged = '[+$count ](bright-black)'
# renamed = '[➜$count ](bright-black)'
# deleted = '[-$count ](bright-black)'
untracked = '[● $count ](green)'
modified = '[● $count ](yellow)'
staged = '[● $count ](orange)'
renamed = '[○ $count ](yellow)'
deleted = '[● $count ](red)'

[cmd_duration]
style = "bright-black"
format = '[$duration]($style)'
